[package]
edition = "2021"

name = "vsmtp-rule-engine"
version = "1.2.1"
license = "GPL-3.0-only"

rust-version = "1.60"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-rule-engine/"

readme = "../../../README.md"
keywords = [
  "vsmtp",
  "scripting-engine",
  "scripting-language",
  "scripting",
  "rhai",
]
categories = ["config"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", default-features = false, version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", default-features = false, version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-config = \\{ path = \"../vsmtp-config\", default-features = false, version = .*", replace = "vsmtp-config = { path = \"../vsmtp-config\", default-features = false, version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-mail-parser = \\{ path = \"../vsmtp-mail-parser\", default-features = false, version = .*", replace = "vsmtp-mail-parser = { path = \"../vsmtp-mail-parser\", default-features = false, version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-auth = \\{ path = \"../vsmtp-auth\", default-features = false, version = .*", replace = "vsmtp-auth = { path = \"../vsmtp-auth\", default-features = false, version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", default-features = false, version = "1.2.1" }
vsmtp-config = { path = "../vsmtp-config", default-features = false, version = "1.2.1" }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser", default-features = false, version = "1.2.1" }
vsmtp-auth = { path = "../vsmtp-auth", default-features = false, version = "1.2.1" }

tracing = "0.1.36"

thiserror = "1.0.32"
# objects
regex = "1.6.0"
iprange = "0.6.7"
ipnet = "2.5.0"
csv = "1.1"

addr = { version = "0.15.4" }

rhai = { version = "1.9.0", features = [
  "unchecked",
  "sync",
  "internals",
  "no_closure",
] }

strum = { version = "0.24.1", features = ["derive"] }

wait-timeout = "0.2.0"

hostname = "0.3.1"
time = { version = "0.3.14", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }

trust-dns-resolver = "0.21.2"

[dev-dependencies]
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }
vsmtp-test = { path = "../vsmtp-test" }

[features]
default = ["vsmtp-common/gsasl_bindgen"]

# TODO: improve that
[package.metadata.docs.rs]
features = []
all-features = false
no-default-features = true
