[package]
edition = "2021"

name = "vsmtp-test"
version = "1.3.0"
license = "GPL-3.0-only"

rust-version = "1.62.1"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"
homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"

publish = false

[dependencies]
vsmtp-common = { path = "../vsmtp-common" }
vsmtp-config = { path = "../vsmtp-config" }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }
vsmtp-rule-engine = { path = "../vsmtp-rule-engine" }
vsmtp-server = { path = "../vsmtp-server" }
vqueue = { path = "../../vqueue" }

async-trait = "0.1.57"
pretty_assertions = "1.3.0"
lettre = { version = "0.10.1", default-features = false, features = [
  "smtp-transport",
  "builder",
  "tokio1-rustls-tls",
  "tracing",
] }

tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.1"


rsasl = { version = "2.0.0-rc.1", features = ["provider"] }
anyhow = "1.0.65"

serde_json = "1.0.85"

tokio = { version = "1.21.1", default-features = false, features = [
  "macros",
  "sync",
  "fs",
  "libc",
  "mio",
  "rt-multi-thread",
] }
base64 = "0.13.0"
