[package]
edition = "2021"

name = "vsmtp-delivery"
version = "1.3.0"
license = "GPL-3.0-only"

rust-version = "1.62.1"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-delivery/"

readme = "../../../README.md"
keywords = ["vsmtp"]
categories = ["network-programming"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-config = \\{ path = \"../vsmtp-config\", version = .*", replace = "vsmtp-config = { path = \"../vsmtp-config\", version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.3.0" }
vsmtp-config = { path = "../vsmtp-config", version = "1.3.0" }

async-trait = { version = "0.1.57", default-features = false }
anyhow = { version = "1.0.65", default-features = false, features = ["std"] }

tracing = { version = "0.1.36", default-features = false, features = ["std"] }
log = { version = "0.4.17", default-features = false, features = ["std"] }

time = { version = "0.3.14", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }
addr = { version = "0.15.6", default-features = false, features = [
  "std",
  # "serde", # TODO
] }

users = { version = "0.11.0", default-features = false }
trust-dns-resolver = { version = "0.21.2", default-features = false, features = [
  "dns-over-rustls",
  "dnssec-ring",
] }
lettre = { version = "0.10.0", default-features = false, features = [
  "smtp-transport",
  "builder",
  "tokio1-rustls-tls",
  "tracing",
  "pool",
] }

tokio = { version = "1.21.1", default-features = false, features = [
  "macros",
  "sync",
  "fs",
  "libc",
  "mio",
  "rt-multi-thread",
] }
