version_requirement = ">=1.3.0-rc.0, <2.0.0"

[server.logs]
filepath = "/var/log/vsmtp/vsmtp.log"

level = [
    "default=warn",
    "receiver=info",
    "rule_engine=warn",
    "delivery=error",
    "parser=trace",
]

[server.smtp.codes]
Greetings = "220 {domain} ESMTP Service ready"

[server.smtp.codes.Help]
code = 214
text = """
This server supports the following commands
HELO EHLO STARTTLS RCPT DATA RSET MAIL QUIT HELP AUTH"""

[server.smtp.codes.TlsRequired]
code = 451
enhanced = "5.7.3"
text = "STARTTLS is required to send mail"

[app.logs]
filepath = "/var/log/vsmtp/app.log"
