version_requirement = ">=1.3.0-rc.0, <2.0.0"

# Global configuration
[server]
domain = "doe-family.com"

[server.interfaces]
# Replace 192.168.1.254 by your own IP.
addr = ["192.168.1.254:25", "192.168.1.254:10025"]
addr_submission = ["192.168.1.254:587"]
addr_submissions = ["192.168.1.254:465"]

[server.tls]
security_level = "May"
preempt_cipherlist = false
handshake_timeout = "200ms"
protocol_version = ["TLSv1.2", "TLSv1.3"]
certificate = "../../../examples/config/tls/certificate.crt"
private_key = "../../../examples/config/tls/private_key.key"

[server.queues]
dirpath = "../../../examples/family/spool"

[app]
dirpath = "../../../examples/family/app"

[app.vsl]
filepath = "../../../examples/family/main.vsl"
