version_requirement = ">=1.3.0-rc.0, <2.0.0"

# Global configuration
[server]
domain = "testserver.com"

[server.interfaces]
addr = ["192.168.1.254:25", "192.168.1.254:10025"]
addr_submission = ["192.168.1.254:587"]
addr_submissions = ["192.168.1.254:465"]

# NOTE: `filepath` key use relative paths to automaticaly test our examples.
#        Use absolute or relative paths relative to your own system instead of those.
#
#        (for example: app.vsl.filepath = "/etc/vsmtp/main.vsl")

[server.queues]
dirpath = "../../../examples/dnsbl/spool"

[app]
dirpath = "../../../examples/dnsbl/app"

[app.vsl]
filepath = "../../../examples/dnsbl/main.vsl"
