version_requirement = ">=1.3.0-rc.0, <2.0.0"

# Global configuration
[server]
domain = "testserver.com"

[server.interfaces]
addr = ["192.168.1.254:25", "192.168.1.254:10025"]
addr_submission = ["192.168.1.254:587"]
addr_submissions = ["192.168.1.254:465"]

# NOTE: `certificate`, `private_key` & `filepath` keys use relative paths for
#        to automaticaly test our examples. Use absolute or relative paths
#        relative to your own system instead of those.
#
#        (for example: app.vsl.filepath = "/etc/vsmtp/main.vsl")

[server.tls]
security_level = "May"
preempt_cipherlist = false
handshake_timeout = "200ms"
protocol_version = ["TLSv1.2", "TLSv1.3"]
certificate = "../../../examples/config/tls/certificate.crt"
private_key = "../../../examples/config/tls/private_key.key"

[server.queues]
dirpath = "../../../examples/message/spool"

[app]
dirpath = "../../../examples/message/app"

[app.vsl]
filepath = "../../../examples/message/main.vsl"
