name: CI
"on":
  push:
    branches:
      - "**"
      - "!doc/**"

env:
  RUST_MSRV: 1.62.1
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        include:
          # Workspace stable
          - toolchain: stable
            path: ./Cargo.toml
            # Workspace MSRV
          - toolchain: 1.62.1
            path: ./Cargo.toml
            # Fuzz crate
          - toolchain: nightly
            path: ./fuzz/Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.toolchain }}-${{ matrix.path }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ${{ matrix.path }}
  cargo-udeps:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-udeps
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: udeps
  cargo-deny:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-deny
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: ${{ env.RUST_MSRV }}
          command: check
          arguments: ""
  nextest:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --workspace --all-features
  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-08
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
      - uses: actions-rs/grcov@v0.1
      - uses: codecov/codecov-action@v2
  lints:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: "rustfmt, clippy"
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--all -- --check"
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "--all-targets --all-features -- -D warnings"
  check-doc:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: "--workspace --no-deps --all-features"
        env:
          RUSTDOCFLAGS: -D warnings
