name: Pre-Release
on:
  pull_request:
    branches:
      - "main"

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get bump method
        id: get-bump-method
        run: |
          echo ${{ github.event.pull_request.labels.*.name }}
          if ${{ contains(github.event.pull_request.labels.*.name, 'B-candidate') }}; then
            echo '::set-output name=BUMP::rc'
          elif ${{ contains(github.event.pull_request.labels.*.name, 'B-release') }}; then
            echo '::set-output name=BUMP::release'
          elif ${{ contains(github.event.pull_request.labels.*.name, 'B-patch') }}; then
            echo '::set-output name=BUMP::patch'
          elif ${{ contains(github.event.pull_request.labels.*.name, 'B-minor') }}; then
            echo '::set-output name=BUMP::minor'
          elif ${{ contains(github.event.pull_request.labels.*.name, 'B-major') }}; then
            echo '::set-output name=BUMP::major'
          else
            exit 1
          fi
      - run: echo ${{ steps.get-bump-method.outputs.BUMP }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-release
      - run: cargo release ${{ steps.get-bump-method.outputs.BUMP }} --workspace --allow-branch "HEAD"
  check-deb-pkg:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install lintian
        run: sudo apt-get update && sudo apt-get install -y lintian
      - uses: Swatinem/rust-cache@v2
      - run: |
          git clone https://github.com/viridIT/cargo-deb.git
          cd cargo-deb
          git checkout fix/changelog-path
          cargo build
          cd ..
      - run: ./cargo-deb/target/debug/cargo-deb -p vsmtp -v
      - run: lintian ./target/debian/*.deb
