name: build release and push to docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Derive version from Cargo.toml
        run: |
          VERSION=$(sed -n "s/^version = \"\(\S*\)\"$/\1/p" Cargo.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: "viridIT/vSMTP:${{ env.VERSION }}"