[package]
edition = "2021"

name = "vsmtp-common"
version = "1.3.0"
license = "GPL-3.0-only"

rust-version = "1.62.1"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-common/"

readme = "../../../README.md"
keywords = ["vsmtp", "smtp", "mail"]
categories = ["data-structures"]

[package.metadata.release]
pre-release-replacements = [
    { file = "Cargo.toml", search = "vsmtp-auth = \\{ path = \"../vsmtp-auth\", version = .*", replace = "vsmtp-auth = { path = \"../vsmtp-auth\", version = \"{{version}}\" }", prerelease = true },
    { file = "Cargo.toml", search = "vsmtp-mail-parser = \\{ path = \"../vsmtp-mail-parser\", version = .*", replace = "vsmtp-mail-parser = { path = \"../vsmtp-mail-parser\", version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-auth = { path = "../vsmtp-auth", version = "1.3.0" }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser", version = "1.3.0" }

anyhow = { version = "1.0.65", default-features = false, features = ["std"] }
log = { version = "0.4.17", default-features = false, features = ["std"] }
serde_json = { version = "1.0.85", default-features = false, features = [
    "std",
] }
addr = { version = "0.15.6", default-features = false, features = [
    "std",
    # "serde", # TODO
] }

strum = { version = "0.24.1", default-features = false, features = [
    "std",
    "derive",
] }
libc = { version = "0.2.133", default-features = false, features = ["std"] }
lettre = { version = "0.10.0", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1-rustls-tls",
    "tracing",
    "pool",
] }
tokio = { version = "1.21.1", default-features = false, features = [
    "macros",
    "sync",
    "fs",
    "libc",
    "mio",
] }
serde = { version = "1.0.144", default-features = false, features = [
    "std",
    "derive",
] }
serde_with = { version = "2.0.1", default-features = false, features = [
    "std",
    "macros",
] }

either = { version = "1.8.0", default-features = false, features = ["serde"] }

base64 = { version = "0.13.0", default-features = false }

[dev-dependencies]
users = { version = "0.11.0", features = [] }
pretty_assertions = "1.3.0"
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }
